### ISSUE TITLE
Could I build a PXE image with this?

### ISSUE THREAD

**Issue by bbigras** [matthewbauer/nixiosk#14]
I would like to be able to have a derivation that I would use directly with `services.pixiecore`.

For x86_64.

**Comment by matthewbauer** [comment]
I don't think it would be too hard - we just need a "pxe" boot target.

**Comment by matthewbauer** [comment]
I have a WIP pxe support here: https://github.com/matthewbauer/nixiosk/pull/15

Could you check it out? I'm not 100% familiar with how pxe is supposed to work, but it is at least able to invoke pixiecore for you.

**Comment by bbigras** [comment]
Oh awesome. Is there also a way to test with qemu?

**Comment by matthewbauer** [comment]
> Oh awesome. Is there also a way to test with qemu?
> 
> EDIT: I mean test nixiosk with qemu, and when happy generate the pxe thing.

I think that would be possible. I've just been building stuff with VirtualBox since I'm more familiar with that. You might want to try to mess around with https://github.com/matthewbauer/nixiosk/blob/305745dae940718006bf743280158cca4ace7e4a/qemu.sh and see if that can work for you.

**Comment by bbigras** [comment]
Thank you so much.

I'm running it right now. It's building a lot of stuff even if I'm using https://nixiosk.cachix.org.

**Comment by bbigras** [comment]
It's weird. It was building for hours and hours.

**Comment by bbigras** [comment]
Any idea why it had to build so much? I'm using nixos-unstable.

**Comment by matthewbauer** [comment]
Sorry - yeah there's some significant changes that require a mass rebuild. nixiosk was not updated for it, but it should have it now (you may need to do `cachix use nixiosk` again - i had to change the signing key).

**Comment by bbigras** [comment]
No worries :smile: 

Thank you very much.

**Comment by bbigras** [comment]
It still has a lot to build. I saw that some things were fetched from the cache but it's still building right now.

Unless maybe it's still using the old cache key. I updated it but I'm using nixus so maybe I did it wrong.

**Comment by matthewbauer** [comment]
Does `nix show-config | grep nixiosk.cachix.org-1:pyzRzjCUhw0r+moXnSklZwwI/gFk+Z+A2ofmEhOf7Sc=` give a result? It may also have a slight delay for all of the cache to be recognized by cachix.

**Comment by bbigras** [comment]
Yes it's there. Weird.

**Comment by matthewbauer** [comment]
There was a bug with GTK3 where it wasn't registering inputs. That should be fixed with the update to wlroots 0.12.

I was also able to boot a VirtualBox from pixiecore though!

**Comment by matthewbauer** [comment]
There was a bug with GTK3 where it wasn't registering inputs. That should be fixed with the update to wlroots 0.12.

I was also able to boot pixiecore on
