### ISSUE TITLE
aarch64-linux missing in flake.nix

### ISSUE THREAD

**Issue by ingenieroariel** [matthewbauer/nixiosk#22]
Hey Matt!

I tried this on an Apple M1 running NixOS and flake.nix does not list it.

I changed it to this and now testing the build.

```
    systems = [ "x86_64-linux" "x86_64-darwin" "aarch64-darwin" "aarch64-linux" ];
```

**Comment by matthewbauer** [comment]
Thanks Ariel for the heads up!

lI believe this stuff still works well, although I haven't tried it on real hardware very recently. I will probably need update Nixpkgs pretty soon.
